# Generated by Django 3.0.7 on 2020-06-10 15:32

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('python', 'python'), ('django', 'django'), ('ui', 'ui'), ('restapi', 'restapi'), ('flask', 'flask'), ('mysql', 'mysql')], max_length=200)),
                ('trainers', multiselectfield.db.fields.MultiSelectField(choices=[('narayana', 'narayana'), ('mahesh', 'mahesh'), ('mohanreddy', 'mohanreddy'), ('srinivas', 'srinivas'), ('wilison', 'wilison')], max_length=200)),
                ('locations', multiselectfield.db.fields.MultiSelectField(choices=[('hyd', 'hyd'), ('bang', 'bang'), ('pune', 'pune'), ('delhi', 'delhi'), ('chennai', 'chennai')], max_length=200)),
                ('shifts', multiselectfield.db.fields.MultiSelectField(choices=[('morning', 'morning'), ('afternoon', 'afternoon'), ('evening', 'evening'), ('night', 'night')], max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('start_date', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='coursesdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('start_data', models.DateField(max_length=100)),
                ('start_time', models.TimeField(max_length=100)),
                ('trainer_name', models.CharField(max_length=100)),
                ('trainer_exp', models.CharField(max_length=100)),
                ('content', models.FileField(upload_to='contents')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
    ]
