# Generated by Django 3.0.7 on 2020-06-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
