# Generated by Django 3.0.7 on 2020-06-04 04:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enquarydata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=60)),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('python', 'python'), ('django', 'django'), ('ui', 'ui'), ('restapi', 'restapi')], max_length=200)),
                ('trainers', multiselectfield.db.fields.MultiSelectField(choices=[('sai', 'sai'), ('nani', 'nani'), ('satya', 'satya')], max_length=200)),
                ('locations', multiselectfield.db.fields.MultiSelectField(choices=[('srnagar', 'srnagar'), ('madhapur', 'madhapur'), ('kphb', 'kphb')], max_length=200)),
                ('gender', models.CharField(max_length=60)),
                ('start_date', models.DateField(max_length=100)),
            ],
        ),
    ]
