# Generated by Django 3.0.7 on 2020-08-23 10:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('enquaryformappp', '0002_auto_20200823_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquarydata',
            name='trainers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mani', 'mani'), ('chinna', 'chinna'), ('siva', 'siva')], max_length=200),
        ),
    ]
